receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/clear:
    endpoint: ${env:GROUNDTRUTH_OTLP_HTTP_ENDPOINT}
    headers:
      x-clear-ingest-key: ${env:GROUNDTRUTH_INGEST_KEY}
    compression: gzip

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/clear]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/clear]
    traces:
      receivers: [otlp]
      exporters: [otlphttp/clear]
