/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 19ff5e8a34c6c047b80ee648a4b0b73c)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  GROUNDTRUTH_API_ORIGIN: string;
  GROUNDTRUTH_SITE_HANDOFF_SECRET: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GROUNDTRUTH_API_ORIGIN" | "GROUNDTRUTH_SITE_HANDOFF_SECRET">
  > {}
}
